/* File generated by gen_cfile.py. Should not be modified. */

#ifndef EDS_MASTER_H
#define EDS_MASTER_H

#include "../third_party/include/data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 eds_master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * eds_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data eds_master_Data;
extern INTEGER32 tc48_status_status;		/* Mapped at index 0x2600, subindex 0x01 */
extern INTEGER32 tc48_status_events;		/* Mapped at index 0x2600, subindex 0x02 */
extern UNS8 tc48_status_sensors[32];		/* Mapped at index 0x2600, subindex 0x03 */
extern INTEGER32 tc48_status_motor;		/* Mapped at index 0x2600, subindex 0x04 */
extern INTEGER32 tc48_status_warning;		/* Mapped at index 0x2600, subindex 0x05 */
extern INTEGER32 tc48_module_reset_err_code;		/* Mapped at index 0x2601, subindex 0x01 */
extern INTEGER32 tc48_module_reset_status;		/* Mapped at index 0x2601, subindex 0x02 */
extern INTEGER32 tc48_scheme_run_err_code;		/* Mapped at index 0x2602, subindex 0x01 */
extern INTEGER32 tc48_scheme_run_status;		/* Mapped at index 0x2602, subindex 0x02 */
extern INTEGER32 tc48_scheme_stop_err_code;		/* Mapped at index 0x2603, subindex 0x01 */
extern INTEGER32 tc48_scheme_stop_status;		/* Mapped at index 0x2603, subindex 0x02 */
extern INTEGER32 tc48_lid_open_err_code;		/* Mapped at index 0x2604, subindex 0x01 */
extern INTEGER32 tc48_lid_open_status;		/* Mapped at index 0x2604, subindex 0x02 */
extern INTEGER32 tc48_lid_close_err_code;		/* Mapped at index 0x2605, subindex 0x01 */
extern INTEGER32 tc48_lid_close_status;		/* Mapped at index 0x2605, subindex 0x02 */
extern INTEGER32 tc48_heat_lid_on_err_code;		/* Mapped at index 0x2606, subindex 0x01 */
extern INTEGER32 tc48_heat_lid_on_status;		/* Mapped at index 0x2606, subindex 0x02 */
extern INTEGER32 tc48_heat_lid_off_err_code;		/* Mapped at index 0x2607, subindex 0x01 */
extern INTEGER32 tc48_heat_lid_off_status;		/* Mapped at index 0x2607, subindex 0x02 */
extern INTEGER32 tc48_rdml_trans_err_code;		/* Mapped at index 0x2608, subindex 0x01 */
extern INTEGER32 tc48_rdml_trans_status;		/* Mapped at index 0x2608, subindex 0x02 */

#endif // EDS_MASTER_H
