
/* File generated by gen_cfile.py. Should not be modified. */

#include "eds_master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER32 tc48_status_status = 0x0;		/* Mapped at index 0x2600, subindex 0x01 */
INTEGER32 tc48_status_events = 0x0;		/* Mapped at index 0x2600, subindex 0x02 */
UNS8 tc48_status_sensors[32] = {};		/* Mapped at index 0x2600, subindex 0x03 */
INTEGER32 tc48_status_motor = 0x0;		/* Mapped at index 0x2600, subindex 0x04 */
INTEGER32 tc48_status_warning = 0x0;		/* Mapped at index 0x2600, subindex 0x05 */
INTEGER32 tc48_module_reset_err_code = 0x0;		/* Mapped at index 0x2601, subindex 0x01 */
INTEGER32 tc48_module_reset_status = 0x0;		/* Mapped at index 0x2601, subindex 0x02 */
INTEGER32 tc48_scheme_run_err_code = 0x0;		/* Mapped at index 0x2602, subindex 0x01 */
INTEGER32 tc48_scheme_run_status = 0x0;		/* Mapped at index 0x2602, subindex 0x02 */
INTEGER32 tc48_scheme_stop_err_code = 0x0;		/* Mapped at index 0x2603, subindex 0x01 */
INTEGER32 tc48_scheme_stop_status = 0x0;		/* Mapped at index 0x2603, subindex 0x02 */
INTEGER32 tc48_lid_open_err_code = 0x0;		/* Mapped at index 0x2604, subindex 0x01 */
INTEGER32 tc48_lid_open_status = 0x0;		/* Mapped at index 0x2604, subindex 0x02 */
INTEGER32 tc48_lid_close_err_code = 0x0;		/* Mapped at index 0x2605, subindex 0x01 */
INTEGER32 tc48_lid_close_status = 0x0;		/* Mapped at index 0x2605, subindex 0x02 */
INTEGER32 tc48_heat_lid_on_err_code = 0x0;		/* Mapped at index 0x2606, subindex 0x01 */
INTEGER32 tc48_heat_lid_on_status = 0x0;		/* Mapped at index 0x2606, subindex 0x02 */
INTEGER32 tc48_heat_lid_off_err_code = 0x0;		/* Mapped at index 0x2607, subindex 0x01 */
INTEGER32 tc48_heat_lid_off_status = 0x0;		/* Mapped at index 0x2607, subindex 0x02 */
INTEGER32 tc48_rdml_trans_err_code = 0x0;		/* Mapped at index 0x2608, subindex 0x01 */
INTEGER32 tc48_rdml_trans_status = 0x0;		/* Mapped at index 0x2608, subindex 0x02 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 eds_master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 eds_master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 eds_master_iam_a_slave = 0;

TIMER_HANDLE eds_master_heartBeatTimers[16] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 eds_master_obj1000 = 0x0;	/* 0 */
                    subindex eds_master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 eds_master_obj1001 = 0x0;	/* 0 */
                    subindex eds_master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 eds_master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 eds_master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t eds_master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 eds_master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 eds_master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 eds_master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 eds_master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 eds_master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 eds_master_highestSubIndex_obj1016 = 16; /* number of subindex - 1*/
                    UNS32 eds_master_obj1016[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex eds_master_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[7] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[8] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[9] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[10] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[11] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[12] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[13] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[14] },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1016[15] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 eds_master_obj1017 = 0x0;	/* 0 */
                    ODCallback_t eds_master_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex eds_master_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&eds_master_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 eds_master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 eds_master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 eds_master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 eds_master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 eds_master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex eds_master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 eds_master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 eds_master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex eds_master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&eds_master_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 eds_master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 eds_master_obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    ODCallback_t eds_master_Index1280_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 eds_master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 eds_master_obj1281_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    ODCallback_t eds_master_Index1281_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 eds_master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 eds_master_obj1282_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    ODCallback_t eds_master_Index1282_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x612;	/* 1554 */
                    UNS32 eds_master_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x592;	/* 1426 */
                    UNS8 eds_master_obj1283_Node_ID_of_the_SDO_Server = 0x12;	/* 18 */
                    ODCallback_t eds_master_Index1283_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 eds_master_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 eds_master_obj1284_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    ODCallback_t eds_master_Index1284_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 eds_master_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 eds_master_obj1285_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    ODCallback_t eds_master_Index1285_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x622;	/* 1570 */
                    UNS32 eds_master_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x5A2;	/* 1442 */
                    UNS8 eds_master_obj1286_Node_ID_of_the_SDO_Server = 0x22;	/* 34 */
                    ODCallback_t eds_master_Index1286_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1286 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1286_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1286_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1286_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x60E;	/* 1550 */
                    UNS32 eds_master_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x58E;	/* 1422 */
                    UNS8 eds_master_obj1287_Node_ID_of_the_SDO_Server = 0xE;	/* 14 */
                    ODCallback_t eds_master_Index1287_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1287 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1287_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1287_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1287_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1288 :   Client SDO 9 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1288 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1288_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 eds_master_obj1288_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 eds_master_obj1288_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    ODCallback_t eds_master_Index1288_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index1288[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1288 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1288_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1288_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1288_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1289 :   Client SDO 10 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj1289 = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj1289_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj1289_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj1289_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index1289[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj1289 },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1289_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj1289_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj1289_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128A :   Client SDO 11 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128A = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128A_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128A_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128A_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128A },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128A_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128A_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128A_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128B :   Client SDO 12 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128B = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128B_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128B_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128B_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128B },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128B_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128B_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128B_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128C :   Client SDO 13 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128C = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128C_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128C_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128C_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128C },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128C_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128C_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128C_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128D :   Client SDO 14 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128D = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128D_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128D_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128D_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128D },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128D_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128D_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128D_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128E :   Client SDO 15 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128E = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128E_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128E_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128E_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128E },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128E_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128E_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128E_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128F :   Client SDO 16 Parameter. */
                    UNS8 eds_master_highestSubIndex_obj128F = 3; /* number of subindex - 1*/
                    UNS32 eds_master_obj128F_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 eds_master_obj128F_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 eds_master_obj128F_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex eds_master_Index128F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj128F },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128F_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&eds_master_obj128F_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&eds_master_obj128F_Node_ID_of_the_SDO_Server }
                     };

/* index 0x2600 :   Mapped variable tc48_status */
                    UNS8 eds_master_highestSubIndex_obj2600 = 5; /* number of subindex - 1*/
                    ODCallback_t tc48_status_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2600[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2600 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_status_status },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_status_events },
                       { RW, visible_string, 32, (void*)&tc48_status_sensors },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_status_motor },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_status_warning }
                     };

/* index 0x2601 :   Mapped variable tc48_module_reset */
                    UNS8 eds_master_highestSubIndex_obj2601 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_module_reset_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2601[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2601 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_module_reset_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_module_reset_status }
                     };

/* index 0x2602 :   Mapped variable tc48_scheme_run */
                    UNS8 eds_master_highestSubIndex_obj2602 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_scheme_run_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2602[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2602 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_scheme_run_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_scheme_run_status }
                     };

/* index 0x2603 :   Mapped variable tc48_scheme_stop */
                    UNS8 eds_master_highestSubIndex_obj2603 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_scheme_stop_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2603[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2603 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_scheme_stop_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_scheme_stop_status }
                     };

/* index 0x2604 :   Mapped variable tc48_lid_open */
                    UNS8 eds_master_highestSubIndex_obj2604 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_lid_open_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2604[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2604 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_lid_open_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_lid_open_status }
                     };

/* index 0x2605 :   Mapped variable tc48_lid_close */
                    UNS8 eds_master_highestSubIndex_obj2605 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_lid_close_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2605[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2605 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_lid_close_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_lid_close_status }
                     };

/* index 0x2606 :   Mapped variable tc48_heat_lid_on */
                    UNS8 eds_master_highestSubIndex_obj2606 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_heat_lid_on_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2606[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2606 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_heat_lid_on_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_heat_lid_on_status }
                     };

/* index 0x2607 :   Mapped variable tc48_heat_lid_off */
                    UNS8 eds_master_highestSubIndex_obj2607 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_heat_lid_off_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2607[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2607 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_heat_lid_off_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_heat_lid_off_status }
                     };

/* index 0x2608 :   Mapped variable tc48_rdml_trans */
                    UNS8 eds_master_highestSubIndex_obj2608 = 2; /* number of subindex - 1*/
                    ODCallback_t tc48_rdml_trans_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex eds_master_Index2608[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&eds_master_highestSubIndex_obj2608 },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_rdml_trans_err_code },
                       { RW, int32, sizeof (INTEGER32), (void*)&tc48_rdml_trans_status }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable eds_master_objdict[] = 
{
  { (subindex*)eds_master_Index1000,sizeof(eds_master_Index1000)/sizeof(eds_master_Index1000[0]), 0x1000},
  { (subindex*)eds_master_Index1001,sizeof(eds_master_Index1001)/sizeof(eds_master_Index1001[0]), 0x1001},
  { (subindex*)eds_master_Index1016,sizeof(eds_master_Index1016)/sizeof(eds_master_Index1016[0]), 0x1016},
  { (subindex*)eds_master_Index1017,sizeof(eds_master_Index1017)/sizeof(eds_master_Index1017[0]), 0x1017},
  { (subindex*)eds_master_Index1018,sizeof(eds_master_Index1018)/sizeof(eds_master_Index1018[0]), 0x1018},
  { (subindex*)eds_master_Index1200,sizeof(eds_master_Index1200)/sizeof(eds_master_Index1200[0]), 0x1200},
  { (subindex*)eds_master_Index1280,sizeof(eds_master_Index1280)/sizeof(eds_master_Index1280[0]), 0x1280},
  { (subindex*)eds_master_Index1281,sizeof(eds_master_Index1281)/sizeof(eds_master_Index1281[0]), 0x1281},
  { (subindex*)eds_master_Index1282,sizeof(eds_master_Index1282)/sizeof(eds_master_Index1282[0]), 0x1282},
  { (subindex*)eds_master_Index1283,sizeof(eds_master_Index1283)/sizeof(eds_master_Index1283[0]), 0x1283},
  { (subindex*)eds_master_Index1284,sizeof(eds_master_Index1284)/sizeof(eds_master_Index1284[0]), 0x1284},
  { (subindex*)eds_master_Index1285,sizeof(eds_master_Index1285)/sizeof(eds_master_Index1285[0]), 0x1285},
  { (subindex*)eds_master_Index1286,sizeof(eds_master_Index1286)/sizeof(eds_master_Index1286[0]), 0x1286},
  { (subindex*)eds_master_Index1287,sizeof(eds_master_Index1287)/sizeof(eds_master_Index1287[0]), 0x1287},
  { (subindex*)eds_master_Index1288,sizeof(eds_master_Index1288)/sizeof(eds_master_Index1288[0]), 0x1288},
  { (subindex*)eds_master_Index1289,sizeof(eds_master_Index1289)/sizeof(eds_master_Index1289[0]), 0x1289},
  { (subindex*)eds_master_Index128A,sizeof(eds_master_Index128A)/sizeof(eds_master_Index128A[0]), 0x128A},
  { (subindex*)eds_master_Index128B,sizeof(eds_master_Index128B)/sizeof(eds_master_Index128B[0]), 0x128B},
  { (subindex*)eds_master_Index128C,sizeof(eds_master_Index128C)/sizeof(eds_master_Index128C[0]), 0x128C},
  { (subindex*)eds_master_Index128D,sizeof(eds_master_Index128D)/sizeof(eds_master_Index128D[0]), 0x128D},
  { (subindex*)eds_master_Index128E,sizeof(eds_master_Index128E)/sizeof(eds_master_Index128E[0]), 0x128E},
  { (subindex*)eds_master_Index128F,sizeof(eds_master_Index128F)/sizeof(eds_master_Index128F[0]), 0x128F},
  { (subindex*)eds_master_Index2600,sizeof(eds_master_Index2600)/sizeof(eds_master_Index2600[0]), 0x2600},
  { (subindex*)eds_master_Index2601,sizeof(eds_master_Index2601)/sizeof(eds_master_Index2601[0]), 0x2601},
  { (subindex*)eds_master_Index2602,sizeof(eds_master_Index2602)/sizeof(eds_master_Index2602[0]), 0x2602},
  { (subindex*)eds_master_Index2603,sizeof(eds_master_Index2603)/sizeof(eds_master_Index2603[0]), 0x2603},
  { (subindex*)eds_master_Index2604,sizeof(eds_master_Index2604)/sizeof(eds_master_Index2604[0]), 0x2604},
  { (subindex*)eds_master_Index2605,sizeof(eds_master_Index2605)/sizeof(eds_master_Index2605[0]), 0x2605},
  { (subindex*)eds_master_Index2606,sizeof(eds_master_Index2606)/sizeof(eds_master_Index2606[0]), 0x2606},
  { (subindex*)eds_master_Index2607,sizeof(eds_master_Index2607)/sizeof(eds_master_Index2607[0]), 0x2607},
  { (subindex*)eds_master_Index2608,sizeof(eds_master_Index2608)/sizeof(eds_master_Index2608[0]), 0x2608},
};

const indextable * eds_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1016: i = 2;break;
		case 0x1017: i = 3;*callbacks = eds_master_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1280: i = 6;*callbacks = eds_master_Index1280_callbacks; break;
		case 0x1281: i = 7;*callbacks = eds_master_Index1281_callbacks; break;
		case 0x1282: i = 8;*callbacks = eds_master_Index1282_callbacks; break;
		case 0x1283: i = 9;*callbacks = eds_master_Index1283_callbacks; break;
		case 0x1284: i = 10;*callbacks = eds_master_Index1284_callbacks; break;
		case 0x1285: i = 11;*callbacks = eds_master_Index1285_callbacks; break;
		case 0x1286: i = 12;*callbacks = eds_master_Index1286_callbacks; break;
		case 0x1287: i = 13;*callbacks = eds_master_Index1287_callbacks; break;
		case 0x1288: i = 14;*callbacks = eds_master_Index1288_callbacks; break;
		case 0x1289: i = 15;break;
		case 0x128A: i = 16;break;
		case 0x128B: i = 17;break;
		case 0x128C: i = 18;break;
		case 0x128D: i = 19;break;
		case 0x128E: i = 20;break;
		case 0x128F: i = 21;break;
		case 0x2600: i = 22;*callbacks = tc48_status_callbacks; break;
		case 0x2601: i = 23;*callbacks = tc48_module_reset_callbacks; break;
		case 0x2602: i = 24;*callbacks = tc48_scheme_run_callbacks; break;
		case 0x2603: i = 25;*callbacks = tc48_scheme_stop_callbacks; break;
		case 0x2604: i = 26;*callbacks = tc48_lid_open_callbacks; break;
		case 0x2605: i = 27;*callbacks = tc48_lid_close_callbacks; break;
		case 0x2606: i = 28;*callbacks = tc48_heat_lid_on_callbacks; break;
		case 0x2607: i = 29;*callbacks = tc48_heat_lid_off_callbacks; break;
		case 0x2608: i = 30;*callbacks = tc48_rdml_trans_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &eds_master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status eds_master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index eds_master_firstIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index eds_master_lastIndex = {
  5, /* SDO_SVR */
  21, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 eds_master_ObjdictSize = sizeof(eds_master_objdict)/sizeof(eds_master_objdict[0]); 

CO_Data eds_master_Data = CANOPEN_NODE_DATA_INITIALIZER(eds_master);

